### ISSUE TITLE
Very first level I could not swipe between circles.

### ISSUE THREAD

**Issue by basvandenberg** [ITKosta829/Nap-N-Ride#1]
Hi Dean Siroky,

I would be very interested to get some more details about the issue you experienced with the Hashi Puzzle app for Android. Going through the reviews there are several 5-star reviews from users with a Samsung Galaxy S20+, yet you mention the following:

> Very first level I could not swipe between circles. Lines were going on random circles. Nothing wrong with my screen.

I tried myself on a Galaxy S20+, and everything works fine.

@ITKosta829 Can you explain what happens if you draw a bridge in Easy #1 from the top left island (4) downwards (towards the island with 3)?

Kind regards,
Bas

**Comment by basvandenberg** [comment]
I am still very much interested to get some more details from you @ITKosta829.

**Comment by ITKosta829** [comment]
Hello Bastiaan,

Thanks for taking the time to write to me.  I'm sorry that I missed your
email 7 days ago.  I would first like to say that I was very much
interested in the game and generally give 4 and 5 star reviews, but for the
fact that I could not even get touch to respond properly there was nothing
else for me to do.  I have since uninstalled the game, but can give it
another try.  I was at one point in time an android developer unable to
break into the market and since moved on, but I would like to assist if I
can.  Please let me know how I would be able to record my screen while
interacting with the game.

Best,
Dean
ᐧ

**Comment by ITKosta829** [comment]
I just downloaded the app again and it's doing the same thing. It's not
playable for me. My one star review will stay, and I'm sorry that it's not
fake to be removed.  Let me know where I can send you a video. I will take
it with another device and share with you via Google drive link.

Dean

**Comment by basvandenberg** [comment]
Hi Dean,

Thanks for your response. I am sorry that I contacted you like this, and
that I have been a bit harsh. I hope you are willing to answer a few
questions to clear this up.

- According to the review details, you are using a Samsung Galaxy S20, is
that correct?

- Just to be sure, bridges are drawn with a short swipe from one island
towards another island. Is this how you try to draw bridges?

- What is exactly going wrong? In your email you say that the touch does
not respond properly, in your review you say that lines go on random
bridges. Could you give a concrete example?

It would be great if you could make a short video of the observed behavior,
you can share the link (or send the video) to my gmail address (bbrennerdd at gmail dot com).

**Comment by ITKosta829** [comment]
Your email address came up as ***@***.***

You can write to me at dcsiroky at gmail dot com (<-- email address written
in case it's removed)  I will try to take a video at some point today and
have it ready.
ᐧ
